ecommerce/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_details, name='cartdetails'),
    path('add/<int:product_id>', views.add_cart, name='add'),
    path('reduce/<int:product_id>', views.reduce_quantity, name='reduce'),
    path('delete/<int:product_id>', views.remove_product, name='delete'),
]

ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('shop/', include('shop.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('', views.searchapp, name='searchapp'),
]

ecommerce/shop/urls.py
from django.urls import path

from shop import views

app_name = 'shop'
urlpatterns = [
    path('', views.allprodcat, name='allprodcat'),
    path('<slug:c_slug>/', views.allprodcat, name='product_by_category'),
    path('<slug:c_slug>/<slug:p_slug>/', views.prodetail, name='procatdetail'),

]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product


# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id


class Cart_item(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = "Cart_item"

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/shop/models.py
from django.db import models


# Create your models here.

# Category Table
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop:product_by_category', args=[self.slug])

    def __str__(self):
        return self.name


# Product Table
class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    image = models.ImageField(upload_to='product', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shop:procatdetail', args=[self.category.slug, self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return self.name

ecommerce/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from shop.models import Product
from .models import Cart, Cart_item


# Create your views here.
# Creating Sessiom

def my_cart(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


# add product to cart
def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)

    try:
        cart = Cart.objects.get(cart_id=my_cart(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=my_cart(request))
        cart.save()

    try:
        cart_item = Cart_item.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
            cart_item.save()
    except Cart_item.DoesNotExist:
        cart_item = Cart_item.objects.create(product=product, cart=cart, quantity=1)
        cart_item.save()
    return redirect('cart:cartdetails')


# cart details
def cart_details(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=my_cart(request))
        cart_items = Cart_item.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass

    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


# delete product
def remove_product(request, product_id):
    cart = Cart.objects.get(cart_id=my_cart(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = Cart_item.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cartdetails')


# reduce product quantity
def reduce_quantity(request, product_id):
    cart = Cart.objects.get(cart_id=my_cart(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = Cart_item.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cartdetails')

ecommerce/search/views.py
from django.shortcuts import render
from django.db.models import Q
from shop.models import Product


# Create your views here.

def searchapp(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request, 'search.html', {'query': query, 'products': products})

ecommerce/shop/views.py
from django.shortcuts import render, get_object_or_404
from shop.models import Product, Category
from django.core.paginator import Paginator, EmptyPage, InvalidPage


# Create your views here.


def allprodcat(request, c_slug=None):
    c_page = None
    product_list = None
    if c_slug is not None:
        c_page = get_object_or_404(klass=Category, slug=c_slug)
        product_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        product_list = Product.objects.all().filter(available=True)
    paginator = Paginator(product_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, 'category.html', {'category': c_page, 'products': products})


def prodetail(request, c_slug, p_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=p_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

ecommerce/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  
</head>
<body>
  <div>
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block title %}
    {% endblock %}
    {% block content %}
    {% endblock %}
  </div>
  <div style="position: relative; height: 200px;">
    {% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </div>
</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
cart page
{% endblock %}

{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center"><br>
        <h1 class="text-center">Cart is Empty</h1><br>
        <p class="text-center">
            <a href="{% url 'shop:allprodcat' %}"><b>Start Shoping</b></a>
        </p>
    </div>
</div>

{% else %}
<div>
    <div class="text-center">
        <h1 class="text-center">Your Cart</h1><br>
    </div>
</div>

<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table">
            <thead>
                <tr>
                    <th colspan="5">
                        Your Items
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td><a href="{{ cart_item.product.get_url }}"><img src="{{ cart_item.product.image.url}}" class="float-left rounded" style="height: 100px; width: 100px;" alt="product image"></a></td>
                    <td class="text=left">
                        {{cart_item.product.name}} <br>
                        SKU : {{cart_item.product.id}} <br>
                        Price : {{cart_item.product.price}} <br>
                        Quantity : {{cart_item.quantity}} x ₹ {{ cart_item.product.price }} <br>
                    </td>
                    <td>₹<b>{{ cart_item.sub_total }}</b></td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td><a href="{% url 'cart:add' cart_item.product.id %}"><i class="fa fa-plus"></i></a></td>&nbsp;
                    <td><a href="{% url 'cart:reduce' cart_item.product.id %}"><i class="fa fa-minus"></i></a></td>&nbsp;
                    <td><a href="{% url 'cart:delete' cart_item.product.id %}"><i class="fa fa-trash"></i></a></td>
                    {% else %}
                    <td><a href="{% url 'cart:reduce' cart_item.product.id %}"><i class="fa fa-minus"></i></a></td>&nbsp;
                    <td><a href="{% url 'cart:delete' cart_item.product.id %}"><i class="fa fa-trash"></i></a></td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="col-12 col-lg-6 col-md-12 col-sm-12 text-center"><br>
        <table class="table table-borderless">
            <thead>
                <tr><th>Checkout</th></tr>
            </thead>
            <tbody>
                <tr>
                    <td>Review your Products before Payment</td>
                </tr>
                <tr>
                    <td>Total Amount : <b>{{ total }}</b></td>
                </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'shop:allprodcat' %}" class="btn btn-primary btn-block">Payment</a>
            <a href="{% url 'shop:allprodcat' %}" class="btn btn-secondary btn-block">Continue Shoping</a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}

<!-- Meta description -->
{% block metadescription %}
{% if category %}
    {{ category.description |truncatewords:150 }}
{% else %}
    Welcome to Smart Kart Ecommerce store.
{% endif %}
{% endblock %}

<!-- Block Title -->
{% block title %}
{% if category %}
    {{ category.name }}-SMART KART
{% else %}
    See our New Collections.-SMART KART
{% endif %}
{% endblock %}

<!-- Block Body -->
{% block content %}

<!-- Category -->
<!-- {% if category %}
<div>
    <div>
        <p >
            <a class="navbar-brand" href="{% url 'shop:allprodcat' %}">Our Products</a>
        </p>
    </div>
</div>
{% endif %} -->

{% if category %}
<div>
    <img src="{{ category.image.url }}" alt="{{ category.name }}" width="100%" height="400">
</div>
{% endif %}

{% if category %}
<div>
    <h1 style="text-align: center; margin-bottom: 20px;">{{ category.name }}</h1>
    <!-- <p>{{ category.description }}</p> -->
</div>
{% else %}
<div>
    <img src="{% static 'images/banner.jpg' %}" width="100%" height="250">
</div><br>
<div style="padding: 10px;">
    <h1 style="text-align: center;">Our Product Collections</h1>
    <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at 
        its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as 
        opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing 
        packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' 
        will uncover many web sites still in their infancy.
    </p>
</div>
{% endif %}

<!-- Products -->
<div class="container-fluid" >
    <div class="row mx_auto">
        {% for product in products.object_list %}
        <div class="col-lg-4 col-md-6 col-sm-12">
            <div class="card text-center my_column">
                <a  href="{{ product.get_url }}"><img style="width: min-250px;" class="card-img-top image" src="{{ product.image.url }}" alt="{{ product.name }}"></a>
                <div>
                    <h4 class="card-title">{{ product.name |truncatewords:5 }}</h4>
                    <p class="card-text">{{ product.price }}</p>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{ pg }}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

ecommerce/templates/footer.html
{% load static %}

<div style="position: absolute; bottom: 0; width: 100%; text-align: center;">
    <p>Copyright 1999-2023 by Refsnes Data. All Rights Reserved.<br>
        Smart Kart is Powered by Smart Kart.</p>
</div>

ecommerce/templates/header.html
{% load static %}

<header>
    <div class="nav ">
        <div class="container-fluid" style="background-color: #7D9D9C; position: relative;">
            <a href="{% url 'shop:allprodcat' %}"><img src="{% static 'images/logo.png' %}" alt="logo image" width="300" height="75" ></a>
            <a style="position: absolute; right: 20px; top: 20px; " class="btn btn-warning "  href="#">Login</a>
        </div>
    </div>
</header>

ecommerce/templates/navbar.html
{% load static %}

<!-- <nav class="nav navbar-dark bg-dark">
    <div class="container-fluid" style="padding: 10px;">
        <div style="display: inline-block;">
            <a class="navbar-brand" href="{% url 'shop:allprodcat' %}">All Products</a>
            {% for cat in links %}
            <a class="navbar-brand" href="{{ cat.get_url }}">{{ cat.name }}</a>
            {% endfor %}
        </div>
        {% if count > 0 %}
        <div style="display: inline;"><a class="navbar-brand" href="{% url 'cart:cartdetails' %}"><i class="fa fa-shopping-cart"></i>({{ count }})</a></div>
        {% endif %}
        <div style="display: inline-block; position: absolute; right: 20px;   ">
            <form class="d-flex "  role="search"  action="{% url 'search:searchapp' %}">
                {% csrf_token %}
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
            </form>
        </div>
            
    </div>
</nav>
 -->

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'shop:allprodcat' %}">HOME</a>&nbsp;
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="navbar-brand dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">SHOP</a>
            <ul class="dropdown-menu">
            {% for cat in links %}
              <li><a class="dropdown-item" href="{{ cat.get_url }}">{{ cat.name }}</a></li>
            {% endfor %}
            </ul>
          </li>
          
          <li class="nav-item">
            <a class="navbar-brand" href="{% url 'cart:cartdetails' %}"><i class="fa fa-shopping-cart"></i>{% if count > 0 %}(<span style="color: blue;">{{ count }}</span>){% endif %}</a>
          </li>
          
        </ul>
        <form class="d-flex" role="search" action="{% url 'search:searchapp' %}">
          {% csrf_token %}
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
          <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
        </form>
      </div>
    </div>
  </nav>

 

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {{ product.description |truncatewords:150 }}
{% endblock %}



{% block content %}
<div><div>
    <p><a href="{% url 'shop:allprodcat' %}">Home</a> | <a href="{{ product.category.get_url }}">{{ product.category }}</a> | {{ product.name }}</p>
</div></div><br>
<div class="container">
<div class="row ">
    <div class="col-lg-6 col-md-6 col-sm-12 text-center"><div >
        <img class="prod_img" src="{{ product.image.url }}" alt="{{ product.name }}">
    </div></div>
    <div class="col-lg-6 col-md-6 col-sm-12"><div class="text-justify">
        <h1>{{product.name}}</h1>
        <p>₹ <b>{{product.price}}</b></p>
        <p>Product Description</p>
        <p>{{product.description}}</p>
        {% if product.stock <= 0 %}
            <p><b>Out of Stock</b></p>
        {% else %}
            <a class="btn btn-primary" href="{% url 'cart:add' product.id %}">Add to Cart</a>
        {% endif %}
    </div></div>
</div></div>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    We have variety of Products
{% endblock %}

{% block title %}
    Search
{% endblock %}

{% block content %}
    <div>
        <p class="text-center"> You are searched for "<b>{{query}}</b>"</p>
    </div>
    <div class="container-fluid" >
        <div class="row mx_auto">
            {% for product in products %}
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card text-center my_column">
                    <a  href="{{ product.get_url }}"><img style="width: max-content;" class="card-img-top image" src="{{ product.image.url }}" alt="{{ product.name }}"></a>
                    <div>
                        <h4 class="card-title">{{ product.name |truncatewords:5 }}</h4>
                        <p class="card-text">{{ product.price }}</p>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="row mx-auto">
                <p class="text-center">0 results found</p> 
            </div>
        {% endfor %}
        </div>
        </div>
{% endblock %}